### ISSUE TITLE
Create a .gitignore file 

### ISSUE THREAD

**Issue by atharva0300** [atharva0300/Meme-Generator#1]
Create a git ignore file.

**Comment by unnikrishnan2002** [comment]
Hey @atharva0300 , can I work on this?

**Comment by atharva0300** [comment]
Yup, you can work on this.

**Comment by unnikrishnan2002** [comment]
> Yup, you can work on this.

Done

**Comment by atharva0300** [comment]
Hey @unnikrishnan2002, 
Can you add dependencies, testing, production, misc  files/folders to the .gitignore ?

**Comment by unnikrishnan2002** [comment]
Sure, I will add that.
