### ISSUE TITLE
[Proposal] React Footer Component 

### ISSUE THREAD

**Issue by atharva0300** [atharva0300/Meme-Generator#11]
### Summary ###
Create a responsive and aesthetic react Footer component for the webpage 

### Should Include ### 
links to FAQ page, About us, signin/register, github repo link, socials. 
You can also add more to it. 

### Reference ### 
[https://www.npmjs.com/package/simple-react-footer](url)

### Snapshots ### 
<img src="https://res.cloudinary.com/ditqevvs5/image/upload/v1605490234/simple-react-footer/mainFooter_jlg0hy.png">
<br/><br/>
<img src ="https://res.cloudinary.com/ditqevvs5/image/upload/v1605490234/simple-react-footer/smallerscreen_zywlze.png">

**Comment by tharunbirla** [comment]
@atharva0300 I would like to work on this 🙂

**Comment by aeswibon** [comment]
Can I work on this issue??

**Comment by atharva0300** [comment]
@cp-Coder 
The Footer component, is already created. But if you have an idea, to make it better, you can go ahead with that, and I will reopen this issue.
Let me know on discord.
Happy Coding !
