### ISSUE TITLE
Create a List of Contributors 

### ISSUE THREAD

**Issue by atharva0300** [atharva0300/Meme-Generator#2]
Create a list of Contributors for this project. 
The list should be displayed in a tabular format. 
Info to be included - Name ,  their Github profile link.

**Comment by aeswibon** [comment]
Can I work on this issue??

**Comment by atharva0300** [comment]
Yup, you can work on this.

**Comment by unnikrishnan2002** [comment]
@atharva0300 We can close this issue now I believe

**Comment by james3gh** [comment]
Should I work on this issue using json file and fetching the data ??

**Comment by atharva0300** [comment]
@james3gh 
Sure, you can.
