### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by SachinMittal1766** [atharva0300/Meme-Generator#21]
## Type of the Issue
- [ ] DOCUMENTATION

## Description of the Issue
README file is not updated. I would like to work on it.  pls @atharva0300 assign it to me.

**Comment by unnikrishnan2002** [comment]
Hey @SachinMittal1766 you had to just check the applicable box don't remove them . And don't erase any fields leave it blank if you are not filling the info. Please keep these points in mind😄.

**Comment by SachinMittal1766** [comment]
Sorry for that. pls assign it to me.

**Comment by unnikrishnan2002** [comment]
> Sorry for that. pls assign it to me.

I can't do that . The maintaners will get back to you soon 👍

**Comment by atharva0300** [comment]
Yup Assigned to you @SachinMittal1766
