### ISSUE TITLE
Create a PR template

### ISSUE THREAD

**Issue by unnikrishnan2002** [atharva0300/Meme-Generator#6]
Creating a PR template would make things organized and easy for folks to describe their PR . @atharva0300 @777ahesh  , need your suggestions on this.

**Comment by atharva0300** [comment]
Yup, you can make a PR Template for the repo.
Make sure to add these necessary things.

### PR Template Example.  ### 
1. Related issue - *Description of the problem*
2. Proposed Changes  - *Description of the solution*
3. Additional Info 
4. Checklist 
- [ ] Tests 
- [ ] Transitions 
- [ ] Documentation
5. Screenshots
- Original
- *space for original screenshot*
- Updated 
- *space for updated screenshot*

**Comment by atharva0300** [comment]
You can, even add something more, if you like.

**Comment by unnikrishnan2002** [comment]
Sure 😃
