### ISSUE TITLE
Add header 

### ISSUE THREAD

**Issue by artimanputra** [atharva0300/Meme-Generator#7]
Can you please assign it to me?

**Comment by 777ahesh** [comment]
i have just created an issue for the navbar component should i assign it to you

**Comment by artimanputra** [comment]
> i have just created an issue for the navbar component should i assign it to you

Sure.

**Comment by 777ahesh** [comment]
Yes I have assigned it now you can work on it.
Just try to make the navbar component responsive.
Add home about contact us and workspace as the links to the navbar.

**Comment by artimanputra** [comment]
> Yes I have assigned it now you can work on it. Just try to make the navbar component responsive. Add home about contact us and workspace as the links to the navbar.

Sure👍

**Comment by 777ahesh** [comment]
The Navbar is already added if  you have some different ideas you can go ahead with it.
Or if you have some more ideas to make the Navbar more better you can work on it.

**Comment by artimanputra** [comment]
Okay

**Comment by atharva0300** [comment]
Closing Issue : Navbar is already added.
