### ISSUE TITLE
Create a Responsive Navbar Component for the Meme-Generator 

### ISSUE THREAD

**Issue by 777ahesh** [atharva0300/Meme-Generator#8]
The Navbar should contain Home About Contact us and Workspace Links.
Try to make the Navbar Responsive.

**Comment by unnikrishnan2002** [comment]
Can I work on this issue @777ahesh ?

**Comment by 777ahesh** [comment]
yes definately you can work on it i have assigned it to you...
Happy Coding !!!
If you have any doubts you can connect on discord.

**Comment by unnikrishnan2002** [comment]
Yeah sure 😃
